version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: securityheaderanalyzerdevops
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=dev
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
